version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "13000:3000"
    image: docker.io/study-react:latest
    container_name: study-react-container
    volumes:
      - ./app:/usr/src/app
    extra_hosts:
      - host.docker.internal:host-gateway
    stdin_open: true